version: "2"
services:
    redis:
        image: redis
        networks: 
            - back-end
    db:
        image: postgres:9.4
        networks:
            - back-end
    vote:
        build: ./vote
        networks: 
            - front-end
            - back-end
    result:
        build: ./result
        networks:
            - front-end
            - back-end
            
    worker:
        build: ./worker
        networks:
            - back-end

networks:
    front-end:
    back-end:
